# 信号处理仿真与应用-数字和模拟滤波器-线性系统变换

## zp2ss
#### 质量-弹簧系统的状态空间表示
**与matlab结果一致**

In [4]:
from scipy import signal
import numpy as np
from pprint import pprint

# 设置numpy打印选项以提高输出的可读性
np.set_printoptions(precision=3, suppress=True)

# 定义零点
z = np.array([0, 0])

# 定义多项式系数并计算极点
p = np.roots([1, 0.01, 1])
print(p)

[-0.005+1.j -0.005-1.j]


In [5]:
# 定义增益
k = 1

# 将ZPK表示转换为状态空间表示
A, B, C, D = signal.zpk2ss(z, p, k)

# 美化打印矩阵A, B, C, D
print("矩阵 A:")
pprint(A)
print("\n矩阵 B:")
pprint(B)
print("\n矩阵 C:")
pprint(C)
print("\n矩阵 D:")
pprint(D)

矩阵 A:
array([[-0.01, -1.  ],
       [ 1.  ,  0.  ]])

矩阵 B:
array([[1.],
       [0.]])

矩阵 C:
array([[-0.01, -1.  ]])

矩阵 D:
array([[1.]])
